# --SITE SETTINGS--
title: "Anti-Monumental Intelligence: Exploring a Series of Counter-Monuments to Chicago's Contentious Public History Narratives using Generative-AI"
email: mrovner@lakeforest.edu
description: "'Anti-Monumental' works with AI to critically evaluate Chicago’s public history monuments, and to propose corrective augmentations or new models that better represent the complicated history of race, conquest, and representation in Chicago. The project responds to the city’s commission–the “racial healing and reckoning project”–tasked with evaluating over 500 Chicago monuments. Though seemingly singular, each monument is entangled in complicated and far-reaching histories of exploitation, extraction, and displacement – histories without physical commemoration in the contemporary city. In conversation with an LLM, the project begins to unravel the histories underpinning monuments central to Chicago’s public narrative, to analyze the contemporary public discourse surrounding their preservation or plans for removal, and to connect them to alternative histories of being and belonging. The project experiments with generative AI’s capacity for reading images, through DALL-E, for example, to question identified monuments, and to re-envision them as “antimonuments” to Chicago’s diverse, complicated, difficult, and hidden histories."
baseurl: "/Anti-monumental-intelligence" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_repo: https://github.com/Profrovner/Anti-monumental-intelligence

# --COPYRIGHT-- (Date generated from last build)
copyright_name: 
license: CC BY-NC-SA 4.0

# build settings
markdown: kramdown
encoding: utf-8

# --STYLES--
accent_color: rgba(224,97,0,1)  # accent color can be any css accepted value
accent_font: Della Respira  # Gogle Fonts import link is in head.html. You can specify the accent font here and it will add it to the main.css
base_font: >
  "Lato", sans-serif

# --MAP SETTINGS--
map-tileset: 'https://api.mapbox.com/styles/v1/mrovner/cl2rynqwa000016p6s1b11xjx/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibXJvdm5lciIsImEiOiJja2o4czl3YTQxN25yMnNueTcycGpwczhmIn0.isCatGeyppD7RyIwKJi3Ew'
map-credits: '<a target="_blank" href="https://github.com/kirschbombe/flaneur">Flâneur</a> | Tiles: Mapbox'
minZoom: 0
maxZoom: 20
setView: '[34.021932, -118.284406], 11'  # set map center point and zoom. See http://leafletjs.com/reference-1.2.0.html for more info.
marker-grouping: grouped # sets the default clustering action. Options: grouped, single
  
# Truncates map marker popup on small screens to only display post title
window-height: 600
window-width: 550

# --LINKS--
collections:
  posts:
    output: true
    permalink: /article/:name
  article-index:
    title: Article Index
    output: true
    permalink: /article-index/:name/

permalink: /:categories/:title/

# --MENU--
menu-type: dropdown  # options: dropdown, circle

# settings for circle menu
menu-height: '200px'
menu-width: '200px'
menu-opacity: '.95'

#pages to exclude in menu
exclude_pages: [ "index.html"]
